
// src/components/PrintableWarehouseReport.tsx
'use client';

import type { Warehouse } from '@/lib/types';
import { format } from 'date-fns';

interface PrintableWarehouseReportProps {
  warehouse: Warehouse;
  items: { name: string; quantity: number }[];
  printedBy: string;
  printDate: Date;
}

export function PrintableWarehouseReport({ warehouse, items, printedBy, printDate }: PrintableWarehouseReportProps) {
  return (
    <div style={{ fontFamily: 'Arial, sans-serif', direction: 'ltr', padding: '20px', width: '210mm', margin: '0 auto' }} id="printable-content">
      <style jsx global>{`
        @media print {
          @page {
            size: A4;
            margin: 20mm;
          }
          body {
            -webkit-print-color-adjust: exact;
            color-adjust: exact;
            margin: 0;
          }
          #printable-report-area {
            margin: 0;
            padding: 0;
            width: 100%;
          }
          .print-header, .print-footer {
            text-align: center;
            margin-bottom: 15px;
          }
          .print-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            font-size: 10pt;
          }
          .print-table th, .print-table td {
            border: 1px solid #ccc;
            padding: 8px;
            text-align: left;
          }
          .print-table th {
            background-color: #f0f0f0 !important;
            font-weight: bold;
          }
          .no-print {
            display: none !important;
          }
        }
      `}</style>

      <div className="print-header" style={{ textAlign: 'center', marginBottom: '20px' }}>
        <h1 style={{ fontSize: '18pt', margin: '0 0 5px 0' }}>Warehouse Inventory Summary</h1>
        <p style={{ fontSize: '12pt', margin: '0' }}>Warehouse: {warehouse.name}</p>
      </div>

      <div style={{ marginBottom: '15px', fontSize: '11pt' }}>
        <p><strong>Print Date:</strong> {format(printDate, "yyyy-MM-dd HH:mm:ss")}</p>
        <p><strong>Printed By:</strong> {printedBy}</p>
      </div>

      <h2 style={{ fontSize: '14pt', marginTop: '20px', marginBottom: '10px', borderBottom: '1px solid #eee', paddingBottom: '5px' }}>
        Items List
      </h2>

      {items.length > 0 ? (
        <table className="print-table" style={{ width: '100%', borderCollapse: 'collapse', fontSize: '10pt' }}>
          <thead>
            <tr>
              <th style={{ border: '1px solid #ccc', padding: '8px', textAlign: 'left', backgroundColor: '#f0f0f0' }}>Item Name</th>
              <th style={{ border: '1px solid #ccc', padding: '8px', textAlign: 'right', backgroundColor: '#f0f0f0' }}>Quantity</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item, index) => (
              <tr key={index}>
                <td style={{ border: '1px solid #ccc', padding: '8px', textAlign: 'left' }}>{item.name}</td>
                <td style={{ border: '1px solid #ccc', padding: '8px', textAlign: 'right' }}>{item.quantity}</td>
              </tr>
            ))}
          </tbody>
        </table>
      ) : (
        <p style={{ fontSize: '11pt', textAlign: 'center', marginTop: '20px' }}>No items in this warehouse.</p>
      )}

      <div className="print-footer" style={{ textAlign: 'center', marginTop: '30px', fontSize: '9pt', borderTop: '1px solid #eee', paddingTop: '10px' }}>
        <p>This report was generated by the Stock Pilot Inventory Management System.</p>
      </div>
    </div>
  );
}
